version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: ./update.sh

workflows:
  version: 2
  all:
    jobs:
      - build 
  scheduled:
    triggers:
      - schedule:
          cron: "0-59 * * * *"
          filters:
            branches:
              only: try-schedule-workflow

    jobs:
      - build