version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: curl -H "Content-Type: application/json" --data '{"build": true}' -X POST https://registry.hub.docker.com/u/wreulicke/circleci/trigger/891e084b-58d2-4816-87a2-faee57791375/

workflows:
  version: 2
  all:
    jobs:
      - build 
  scheduled:
    triggers:
      - schedule:
          cron: "0-59 1 * * *"
          filters:
            branches:
              only: try-schedule-workflow

    jobs:
      - build