version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: | 
              if [ $CIRCLE_BRANCH == "master" ]; then
                ./update.sh
              fi 

workflows:
  version: 2
  all:
    jobs:
      - build 
  scheduled:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master

    jobs:
      - build