FROM alpine:3.7

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8
RUN apk add --no-cache \
        ca-certificates \
        curl \
        gnupg \
        libressl \
        tar \
        git \
        mercurial \
        openssh-client \
        subversion \
        procps \
        java